# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goreltest < Formula
  desc ""
  homepage "https://github.com/bradyjoslin"
  version "0.3"

  on_macos do
    on_intel do
      url "https://github.com/bradyjoslin/goreltest/releases/download/v0.3/goreltest_Darwin_x86_64.tar.gz"
      sha256 "4e52c3d67a9a0ee4df71b74331794be6bdcfef4ae0cd749591d21f1d253dea68"

      def install
        bin.install "goreltest"
      end
    end
    on_arm do
      url "https://github.com/bradyjoslin/goreltest/releases/download/v0.3/goreltest_Darwin_arm64.tar.gz"
      sha256 "0a8313c3625a5b8875685e48618dd2350188ee9f5deabd434243ee2fee3a650f"

      def install
        bin.install "goreltest"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/goreltest/releases/download/v0.3/goreltest_Linux_x86_64.tar.gz"
        sha256 "3dd0d29692ff82f46bf5935e85f84e87e91e60c4cf4fedfbf24a6fdd8df2d5b9"

        def install
          bin.install "goreltest"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/goreltest/releases/download/v0.3/goreltest_Linux_arm64.tar.gz"
        sha256 "a33383309a8b8ceb7659eb63a4518377640cb3dcb0feb9598601af20ce7d36dc"

        def install
          bin.install "goreltest"
        end
      end
    end
  end
end
